version: '3'

services:
  genai-research-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Backend API
      - "3000:3000"  # Frontend
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite+aiosqlite:///./app.db}
      - DEBUG=${DEBUG:-false}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - META_API_KEY=${META_API_KEY:-}
      - PYTHONPATH=/app
    volumes:
      - ./tmp:/app/tmp  # Persistent storage for SQLite database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 