---
title: GenAI Research Assistant
emoji: 🔎
colorFrom: indigo
colorTo: purple
sdk: docker
app_port: 7860
pinned: true
license: mit
---

# GenAI Research Assistant

A powerful AI-powered research assistant that helps you search, analyze, and synthesize information from various sources.

## Features

- Multi-model LLM support (OpenAI, Google, Meta)
- Document-based question answering
- Chat memory and conversation history
- Modern React frontend with responsive design

## Environment Setup

To use this application, set the following environment variables in your Hugging Face Space settings:

- `OPENAI_API_KEY`: Your OpenAI API key
- `GOOGLE_API_KEY`: Your Google AI Studio API key
- `META_API_KEY`: Your Meta API key
- `DATABASE_URL`: (Optional) Database connection string

## Learn More

[Visit GitHub Repository](https://github.com/yourusername/genai-research-assistant)

---
*Deployed via GitHub Actions to Hugging Face Spaces* 